### ISSUE TITLE
Zlib::GzipWriter object must be closed explicitly

### ISSUE THREAD

**Issue by dukedave** [jekyll-assets/jekyll-assets#108]
I don't have too much to go on, other than this is 100% reproducible on my machine.

It looks like this:

```
$ jekyll build --watch                                                                                                                                                               
Configuration file: /home/dave/code/mysite/_config.yml
            Source: .
       Destination: ./_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '.'
      Regenerating: 1 files at 2014-11-07 19:00:51 ...error:
             Error: data error
             Error: Run jekyll build --trace for more information.
      Regenerating: 1 files at 2014-11-07 19:01:00 zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream state was inconsistent.
...done.
```

So it builds successfully the first time, but all subsequent builds fail the same way.

It seems to be an issue compressing JS, and my workaround is to disable it in `_config.yml` by changing `gzip: [ text/css, application/javascript ]` to `gzip: [ text/css ]`.

This only happens on my machine, it works as expected on others.
I'm running Ubuntu 14.04, and get:

```
$ gzip --version
gzip 1.6
```

**Comment by bendangelo** [comment]
I'm still getting this issue. I can look into fixing it if work hasn't already started.

**Comment by dukedave** [comment]
@bendangelo still present in 0.10.0 for me, AFAIK no further work has been done.

**Comment by wlaurance** [comment]
Any progress on this one @ixti ?

I suppose we need to call `close` or equivalent on a `Zlib::GzipWriter` object somewhere.

**Comment by dukedave** [comment]
Ah so I put a few hours in to this last week @wlaurance, but I didn't get round to posting my findings!
I'll get to it at some point, but for now: It seems somehow related to encoding.

The call ultimately gets through to [`write_to`](https://github.com/sstephenson/sprockets/blob/1566cd10486b677d52d93c74f489ad7a8d2acd79/lib/sprockets/asset.rb#L140) in sprockets. I found that if I patch `to_s` there and truncated the response to end before an `ö` (which appeared in a comment in the JS causing the failure), it worked.

YMMV :wink:

**Comment by envygeeks** [comment]
This is an upstream issue but since Sprockets 2 is EOL (for what it's worth in Ruby) I'm closing this, if it pops back up once it's reimplemented into sprockets 3 please file a new ticket.

**Comment by dukedave** [comment]
@envygeeks was it actually reported against Sprockets 2?
It being an upstream issue is consistent with what I found, and I'm okay with closing this for that reason, I just wondered for my own peace of mind :innocent:

**Comment by envygeeks** [comment]
I don't know if it was but we are on Sprockets 3 and the version I'll be pushing up this weekend (after I sort out current tickets to push them all onto 2.0.0 and release 1.0.0 as is so we can install the rewrite) we will see if it's still an issue on Sprockets 3 and if it is we can report it upstream and get it fixed in Sprockets 3 at least.

**Comment by dukedave** [comment]
@envygeeks I see the 1.0.0 release on Rubygems, congrats :smile: 
Should if I pull the latest master for jekyll-assets, will that be using Sprockets 3?

**Comment by envygeeks** [comment]
@dukedave the 1.0.0 release pushed out the last-legacy release so that I could merge the new source... it was released as is with what was on master before I merged the rewrite.  The current master is a completely new ground-up rewrite of jekyll-assets with Sprockets 3, a simple but robust uncoupled hook system and full-on Jekyll 3 (only -- there is no Jekyll2 support) support.  I would be cautious of using 2.0.0 unless you read the readme and spot the differences but here are a few:

* We do tags different in 2.0.0 so they are most robust (in that we parse them with Shellwords to give you powerful escaping and formatting.) we use `:` instead of `=`, and we expect the first argument to be a file.
* We have the concept of proxy arguments to give you even more power in the tags, for example you can proxy whitelisted arguments directly into Sprockets (like accept for a custom content type.)
* We have the concept of boolean arguments for both html and proxy arguments.
* We currently do not have image manipulation available in the current master I was literally working on that as you messaged, but when it's released it uses an entirely different library (we use MiniMagick because it's a bit more robust while being memory smaller than rmagick and a bit more powerful than the old library.)
