### ISSUE TITLE
Changes to @import files not being detected by watcher

### ISSUE THREAD

**Issue by dmix** [jekyll-assets/jekyll-assets#143]
I have this structure of scss files:

```
_assets/stylesheets/application.scss
_assets/stylesheets/_layout.scss
_assets/stylesheets/_content.scss
_assets/stylesheets/_elements.scss
```

Within  ***_assets/stylesheets/application.scss*** I import the subdirectory files:

```
@import "application/_content.scss";
@import "application/_layout.scss";
@import "application/_elements.scss";
```

Then I include application.css into my layout.

When I modify ***application.scss*** the css file updates files, but when I update one of the @import files, for example: ***application/_content.scss***, the parent application.css file does get updated to reflect this change. I have to restart my jekyll server to see the change reflected.

Is this a bug with jekyll-assets? Do I really have to keep all the SCSS in one big file?

You can see the live example here: https://github.com/copperhead-security/copperhead.co

**Comment by abeMedia** [comment]
Same problem as I have with imported less files. If you use cache, do you need to delete the cache folder before rebuilding the site?

**Comment by dmix** [comment]
I do not use cache. Sorry can't help you there.

The only solution to the @import issue is to restart the server so it rebuilds the SCSS properly. The watcher doesn't do this.

**Comment by abeMedia** [comment]
I wasn't looking for help, I resorted in turning off cache and rebuilding the site on each change with a custom listener. I Just thought it might help @ixti narrow down the possible causes if it turns out that your bug and https://github.com/jekyll-assets/jekyll-assets/issues/137 are the same thing.

**Comment by ixti** [comment]
Thanks for reports and comments. I will try to resolve this issues as soon as possible (just don't have lots of time these days).

**Comment by envygeeks** [comment]
This is a sprockets problem, this is resolved in the upcoming version and will be fixed once it's merged and the new alpha releases, the way we solved it in the new version is to find the asset and compare the digests since caching works well enough to keep the speed fast and digests will always change if a dependency changes.

**Comment by envygeeks** [comment]
Sorry, I didn't elaborate how it's a sprockets problem.  When I was implementing a Jekyll3 regeneration cacher inside of the new jekyll-assets I noticed that mtime never gets updated if a dependency is updated in Sprockets, this is more than likely a bug somewhere in Sprockets or SASS itself (I don't remember which integrates the other.)  So if you rely on mtime to decide whether an asset has changed you run into problems, the asset is technically updated but the mtime is never updated.

**Comment by abeMedia** [comment]
Excellent news, thanks!
