### ISSUE TITLE
[IDEA] New tag options fortmat

### ISSUE THREAD

**Issue by ixti** [jekyll-assets/jekyll-assets#150]
Right now multiple options (plugins) are separated with comma:

```
{% image foo.jpg [resize:300x200, auto-size] %}
```

That makes it difficult to allow more "complex" params, so instead we can have split them up like this:

```
{% image foo.jpg [resize 300x200] [auto-size] %}
```

NOTE: In case this will happen, old syntax should still be supported till next big release.

**Comment by envygeeks** [comment]
What about this format:

```
{% img foo.jpg resize:300x200 autosize:true %}
```

In the updated version we use Shellwords to process arguments and escapes for `:` so that we can give them powerful syntax like so: https://github.com/jekyll-assets/jekyll3-assets/blob/master/lib/jekyll/assets/tag/parser.rb#L4  I could even modify that so that we can make it autosize instead of autosize true where we just take the first argv as the value and any other as a boolean.
