### ISSUE TITLE
Magick resize not working on windows?

### ISSUE THREAD

**Issue by mykagrove** [jekyll-assets/jekyll-assets#167]
Hi, I can't seem to get magick to resize any images. If I have markup like:
```
{% image test.jpg magick:resize:100x100 %}
```
It compiles without errors but just puts an image with the original dimensions into _site/assets.

Perhaps I have it configured wrong?
I installed ImageMagick-7.0.0-0-Q16-x64-dll.exe
My _config.yml looks like this:
```assets:
  cache: false
  prefix: "/_assets"
  assets:
    - "*.jpg"
  digest: true
  sources:
    - "_assets/stylesheets"
    - "_assets/javascripts"
    - "_assets/images"
```
And in _plugins/ext.rb I have ```require "jekyll-assets"```

**Comment by envygeeks** [comment]
Can you test it with "img" and see if it works? If it does then it's a bug in the parser (which in theory should cache aliases,) if it doesn't then I'll log onto my windows machine sometime today or tomorrow and track the steps to see where it's going wrong.

**Comment by mykagrove** [comment]
Ah, with img it comes up with ``` Liquid Exception: Unknown tag 'img' in ....```
So I must have set it up wrongly ... ?

**Comment by envygeeks** [comment]
How are you installing Jekyll Assets? The current Jekyll assets you wish to use (2.0 alpha) is only available via git so you'll need to either use our https://github.com/jekyll/docker-jekyll with a Gemfile set to `UPDATE_GEMFILE=true` and pre-supply a Gemfile in your root with 'gem "jekyll-assets", :github => "jekyll-assets/jekyll-assets"' or you'll need to simply add a Gemfile with `jekyll` and the aforementioned` and once that's done you'll be on the version you wish to play with.

The version that you are reading in the MD file is the version being released with Jekyll 3.0 (it does not support Jekyll 2.* at all because we use hooks.) If you do not wish to deal with all that you can see the docs for the current version you have installed: https://github.com/jekyll-assets/jekyll-assets/tree/legacy#jekyllassets -- Note, it's syntax is entirely different and it doesn't have tag aliases.

**Comment by mykagrove** [comment]
You know what, that totally explains it. I thought the two versions were interchangeable which is completely stupid. Thank you for the help.

I'm actually getting an error ```identify.exe: Corrupt JPEG data: 6 extraneous bytes before marker``` but that's clearly something completely different and I'll not take up any more of your time, thanks again! :)

**Comment by envygeeks** [comment]
Yeah the syntax changed and isn't backwards compatible because I opted for the more flexible colon based Shellwords parsing which gave extreme flexibility to what you can give me as far as args without complexity.  In that you can pass 'magick:trigger;"hello world"' and it will get parsed out properly as a single argument.  The old syntax would have required a lot of work to do stuff like that and escaping.

**Comment by envygeeks** [comment]
Either way, you didn't take up my time! Thanks for asking!
