### ISSUE TITLE
Connect jekyll-assets 2.0.0.pre.beta

### ISSUE THREAD

**Issue by pustovalov** [jekyll-assets/jekyll-assets#180]
Used these two gems:
```
gem 'jekyll', '~> 3.0.0.pre.beta9'
gem 'jekyll-assets', '~> 2.0.0.pre.beta'
```

And got an error:
```
/Users/pavel/site/source/_plugins/ext.rb:1:in `require': cannot load such file -- jekyll-assets (LoadError)
from /Users/pavel/site/source/_plugins/ext.rb:1:in `<top (required)>'
```

With version 1.0.0, this error is not present.

**Comment by amw** [comment]
You've put `require "jekyll-assets"` in your ext.rb? You don't need to do that. For me it loads automatically.

In either case the required file would be `jekyll/assets`.

**Comment by envygeeks** [comment]
@amw is right, we no longer provide `jekyll-assets` and now use the defacto jekyll/assets since modern bundler works with that (and it's just good file structure.)  If it becomes a major problem I'll readd the file but I would prefer what @amw implied, you don't require it and let bundler autorequire it or you.
